import numpy as np
# a = np.array([[1,2],[3,4]])
# b = np.array([[1,2],[3,4]])
# c = a.dot(b)
# print(a)
# print("``````")
# print(b)
# print("``````")
# print(c)
# b = a.transpose() #转置
# print(a)
# print(b)
# a = np.eye(4)
# b = np.array([(1,2,3),[4,5,6],[7,8,9]])
# print(a.dot(b))
# a = np.array([(1,2,3),(4,5,6)])
# a = np.arange(12).reshape(2,6)
# a = np.zeros((3,4))
# a = np.eye(2)
# a = np.full((2,3),4)
# a = np.empty((2,3))
# a = np.linspace(0,5,3)
# a = np.logspace(0,2,10)
# a = np.random.random((2,3))
# b = np.random.rand(2,5)
# c = np.random.randn(2,5)
# d = np.random.randint(2,5,size=([2,5]))
# a = np.array([(1,2,3),(4,5,6)])
# print(a.shape)
# print(a.size)
# print(a.dtype)
# print(a.dtype.name)
# print(a.astype(int))
# print(a.itemsize)
# print(a.data)
# print(a.ndim)
# print(b)
# print(c)
# print(d)
# arr = np.arange(10)
# # print(arr)
# # print(arr[3:5])
# # print(arr[:5])
# # print(arr[-1])
# # print(arr[2:4])
# # print(arr[1:-1:3])
# arr = np.array([(1,2,3,4,5),(6,7,8,9,10),(11,12,13,14,15)])
# print(arr)
# print(arr[0,3:5])
# print(arr[1:,2:])
# print(arr[(0,1,2),(1,2,3)])
# mask = np.array([1,0,1],dtype = np.bool)
# # print(arr[mask,2])
# a = np.array([(1,2,3),(4,5,6)])
# b = np.array([(7,8,9),(10,11,12)])
# print(np.concatenate((a,b)))
# print(np.concatenate((a,b),axis=0))
# print(np.concatenate((a,b),axis=1))
# print(np.vstack((a,b)))
# # print(np.hstack((a,b)))
# print(np.hsplit(a,3))
# print(np.vsplit(a,2))
# print(np.split(a,2,axis=0))
# print(np.ravel(a))
# print(a.flatten('F'))
# a =[1,2,3]
# b = np.array([4,5,6])
# # b = np.mat(a)
# # print(a)
# data6= np.mat(np.eye(2,2,dtype=int));
# print(data6)
# a=[1,2,3]
# b = np.matrix(a)
# c=[4,5,6]
# d = np.mat(c)
# print(np.bmat("b d;b d"))
# print(b)
# a = np.eye(3)
# print(np.trace(a))
# a = np.array([[1,2],[3,4]])
# b = np.array([5,6])
# print(np.linalg.solve(a,b))
# a = np.mat([[1,2,3],[4,5,6],[7,10,9]])
# print(np.linalg.inv(a))
# print(a)
# print(np.linalg.inv(a))
# u,v = np.linalg.eig(a)
# print(u,v)
# a = np.array([[1,2,3],[3,4,5],[5,6,7]])
# u,v = np.linalg.eig(a)
# print(u,v)
# a = np.array([(1,4,4),(9,9,9),(16,16,16)])
# b = np.array([(1,1,1),(2,2,2),(3,3,3)])
# print(np.add(a,b))
# print(np.subtract(a,b))
# print(np.divide(a,b))
# print(np.multiply(a,b))
# print(np.sqrt(a))
# print(np.power(a,2))
# print(np.sin(a))
# arr = np.loadtxt('mpg.txt',skiprows=1,usecols=range(6))
# print(arr)
# a=np.array([4,3,1,2])
# print(np.argsort(a))
# print(np.log(a))
# print(np.transpose(a))
# print(np.exp(a))
# print(a[np.where(a>5)])
# print(np.sum(a,axis=0))
# print(np.sum(a,axis=1))
# print(np.min(a,axis=0))
# print(np.min(a,axis=1))
# print(np.mean(a))
# print(np.median(a))
# print(np.cumsum(a))
# print(np.diff(a))
# print(np.argmin(a))
# print(np.clip(a,4,6))
# print(np.sort(a))
# print(np.random.randint(2,10,size=([2,5])))
b = np.array([[1.0, 2.0], [3.0, 4.0]])
d = np.linalg.inv(b)
print('b逆矩阵:\n', d)